### PR TITLE
 shorten about me #25 

### LINKED ISSUE #25: shorten about me
- [x] shorten the description for all, a bit hard to read. do a bit of research on how others do it, and try to make it more engaging & can adjust the design/size to make it more pleasing to the eyes.
- [x] on hover of the icon -> change color to blue. change the blue hover color according to logo theme color.

image

### PR DESCRIPTION
**Pull request by NadhirahIzzati**
Screenshot (741)

Screenshot (742)

Screenshot (743)
Screenshot (744)

Screenshot (745)

### CODE REVIEW

**Comment by rosclaritha** [comment]
Location just mention Kota Marudu instead of the specific @NadhirahIzzati

**Comment by NadhirahIzzati** [comment]
Screenshot (746)

**Comment by rosclaritha** [comment]
part below for `project, happy farmes, hours of support` doesn't suit the caption.

**Comment by NadhirahIzzati** [comment]
- changed picture shape
- change wording to fit the caption.
- other suggestion for the wording: 
1) Thriving Community
2) Harvested Hope
3) Knowledge Shared
4) Empowered Farmers
5) Positive Change
6) Environmental Stewardship
7) Improved Livelihoods
8) Organic Growth

Screenshot (752)
Screenshot (753)
Screenshot (754)
Screenshot (755)
Screenshot (756)
Screenshot (757)

**Review by rosclaritha — APPROVED** [review]

**Pull request merged**
